### ISSUE TITLE
StringIndexOutOfBoundsException from RangeApplier.updateImports

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/Srg2Source#12]
Forestry for Minecraft 1.9.4 will not build with gradle due to this error.

Here is the gradle log
 --stacktrace: https://gist.github.com/mezz/882ce4c023d8b6fbbe99fcb66d03ac71
 --stacktrace --info: https://gist.github.com/mezz/973ff1d26cf00ee45d4ceb20cc8d3601
 --stacktrace --debug: https://gist.github.com/mezz/e02199d79a7e573fde8eb3788d846435

It boils down to 
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -280
	at net.minecraftforge.srg2source.rangeapplier.RangeApplier.updateImports(RangeApplier.java:423)
```

**Comment by LexManos** [comment]
This is actually an issue woth your build.gradle you're passing invalid sources into the s2s task.
My lan just died sonima go to bed. But when its back remind me on irc to send you a fixed build.gradle

**Comment by LexManos** [comment]
https://github.com/ForestryMC/ForestryMC/pull/1252
