### ISSUE TITLE
Crash during extractRangemapReplacedMain

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/Srg2Source#18]
I get the following error when trying to `gradle build`:
`Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)`
[full gradle.log](https://gist.github.com/mezz/67e20860ec666bfc88b5349a72968b4f)

Tracing things down, it looked similar to issue #14 so I looked into the logs to see where it was crashing.
From the end of [extractRangemapReplacedMain.log](https://gist.github.com/mezz/2f30cf396fafa1ccd005b76fd97fd83d):
```
startProcessing "binnie\genetics\machine\indexer\ComponentApiaristIndexerInventory.java" md5: ff3f411669dde25aff450713b4898ee0
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
    Compile Error! Pb(883) '<>' operator is not allowed for source level below 1.7
```

That file looks like this on my machine: [ComponentApiaristIndexerInventory.java](https://gist.github.com/mezz/4fa7e8e82a245eb2b39c3446fe815381)

This seems to be caused by the unusual [`SpeciesList` class defined in the switch statement](https://gist.github.com/mezz/4fa7e8e82a245eb2b39c3446fe815381#file-componentapiaristindexerinventory-java-L40). I moved this class out so that it is a `public static class` and the build worked.

**Comment by boq** [comment]
Also #16 duplicate. #17 for proposed fix, though I never got any comments on that

**Comment by mezz** [comment]
Thanks. @AbrarSyed helped me debug this so hopefully he has a chance look over the proposed fix soon. If he's not free I'll bug Lex about it.
