### ISSUE TITLE
No documentation on how to use this.

### ISSUE THREAD

**Issue by chibill** [MinecraftForge/Srg2Source#8]
I can't find any documentation on how to use Srg2Source. Can you please maybe update the readme fill to say how to use this version that does not use python?

**Comment by LexManos** [comment]
Write it

**Comment by chibill** [comment]
I can't because I don't even know how to use it. That's why I made this to get into on how to even use it...

**Comment by LexManos** [comment]
Read how FG uses it.

**Comment by AbrarSyed** [comment]
right now you can only use it as a java library.

On Tue, Apr 21, 2015 at 10:40 PM, Chibill <notifications@github.com> wrote:

> I can't because I don't even know how to use it. That's why I made this to
> get into on how to even use it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MinecraftForge/Srg2Source/issues/8#issuecomment-95016901>
> .
>



-- 
Abrar Syed
https://keybase.io/abrarsyed
https://github.com/abrarsyed

**Comment by chibill** [comment]
Okay. I figured that out a while ago. But thanks for the help so far. I might try based off of how forge gradle uses it make so documentation for you guys.

**Comment by chibill** [comment]
Closing this as it was already answered....
