### ISSUE TITLE
Doesn't handle remapping lambdas or method refs

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/Srg2Source#9]
ForgeGradle uses Srg2Source to create srg named source jars, and later remap those jars to the target mcp snapshot version. Method refs and lambdas aren't getting remapped with the rest of the methods/fields.

**Comment by LexManos** [comment]
Ya it probably doesn't. There's a reason we target Java 6.
Wonder what the AST looks like for this stuff.

**Comment by nallar** [comment]
Related/same issue with lambdas causing an NPE at [SymbolRangeEmitter.java:113](https://github.com/MinecraftForge/Srg2Source/blob/d5036d7db47642460a4e7977b52b727c10791e18/src/main/java/net/minecraftforge/srg2source/ast/SymbolRangeEmitter.java#L113)

This seems to be the simplest class which causes it:
https://gist.github.com/nallar/12e78ab93bf160a6e087

Example repo which encounters the crash on ./gradlew build: [nallar/Srg2SourceCrash](https://github.com/nallar/Srg2SourceCrash)

**Comment by LexManos** [comment]
Issue was in Eclipse's JDT library. Updating it fixed it.
However, it needs more testing as I don't know what bugs updating introduced. 
I don't *think* it added any, or added a hard derp to J8, but needs tests.
